[project]
name = "backgammon"
version = "0.0.1"
requires-python = ">=3.10"

[tool.pytest.ini_options]
addopts = "-q --cov=backgammon --cov-report=term-missing"
testpaths = ["backgammon/tests"]
pythonpath = ["."]
